### PR TITLE
KEP-3935: Generate test configurations for n-3 node skew

### PR DESCRIPTION
**Pull request by liggitt**
Related to [KEP-3935](https://github.com/kubernetes/enhancements/issues/3935)

/hold

### CODE REVIEW

**Comment by pacoxu** [comment]
Link the cluster-lifecyle weekly meeting dicussion on this topic: https://docs.google.com/document/d/1Gmc7LyCIL_148a9Tft7pdhdee0NBHdOfHS1SAF0duI4/edit#bookmark=id.dlswqqyv7xse

Merging this to conduct initial tests can help to identify any potential issues with the new n-3 node skew in current versions. 
I think we can merge this earlier.

**Review by neolit123 — COMMENTED** [review]
/approve
thanks, i think the config changes are accurate.
we should add the diff after kinder/hack/update-workflows.sh as part of this PR

**Comment by liggitt** [comment]
Updated with result of running kinder/hack/update-workflows.sh

**Comment by liggitt** [comment]
> Merging this to conduct initial tests can help to identify any potential issues with the new n-3 node skew in current versions.
> I think we can merge this earlier.

I'm happy to merge early and watch job health if you're up for it. I agree it could help inform discussions of the KEP and flush out issues I might have missed. The only gaps in 1.24 / 1.27 node combinations I know of were 1.24 nodes relying on in-tree AWS or AzureDisk volumes, which isn't an issue for these jobs.

**Comment by liggitt** [comment]
will leave it up to approvers to cancel hold

**Comment by liggitt** [comment]
maybe we can unhold after the 1.27.0 release so if the new job has any issues it won't confuse/muddy informing dashboards ahead of release

**Comment by pacoxu** [comment]
/unhold
as 1.27 is out.

**Comment by liggitt** [comment]
I'm not sure how this translates into the test-infra config for https://testgrid.k8s.io/sig-node-kubelet#Summary

is there another manual step or do we just wait for some job to run to update that config?

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/test-infra/pull/29287

**Pull request merged**
