### PR TITLE
Change ansble use 'include' instead 'import_tasks' or 'include_tasks'

### PR DESCRIPTION
**Pull request by chenyb4**
Signed-off-by: Yuanbin.Chen <cybing4@gmail.com>

### CODE REVIEW

**Comment by stealthybox** [comment]
Related to issue #991 

The `include` module is deprecated in newer versions of ansible but currently still functions:
> This module will still be supported for some time but we are looking at deprecating it in the near future.
https://docs.ansible.com/ansible/2.6/modules/include_module.html

This does resolve the problem though.

**Comment by kad** [comment]
With ansible 2.6 out, and with possibility to use ansible from virtualenvs, I'd suggest not to use deprecated module for just support ansible 2.3 or lower. I'd rather set expectations about supported ansible versions.

**Comment by fabriziopandini** [comment]
@chenyb4 sorry for delay in reviewing this
I agree with @kad the we should't use deprecated modules, so my proposal is to close this PR

FYI  
I'm going to raise at SIG level a discussion about the future of kubeadm-playground which is quickly moving from a rough idea discussed at kubeconf to something bigger. In the long term we should simplify things to make it more easily maintenable and getting rid of ansible dependency is something to tackle asap

**Pull request closed without merging**
