### PR TITLE
delete  go.mod  file in the root  directory

### PR DESCRIPTION
**Pull request by tanjunchen**

### CODE REVIEW

**Comment by tanjunchen** [comment]
@neolit123

**Comment by tanjunchen** [comment]
@hwdef

**Comment by neolit123** [comment]
@tanjunchen please explain why is this needed right now?

**Comment by tanjunchen** [comment]
@neolit123    https://github.com/kubernetes/kubernetes  
 kubernetes has go.mod and go.sum file.
kubernetes/kubeadm has  only go.mod file . Go get kubeadm, each time the local go.sum file will be generated

**Comment by tanjunchen** [comment]
@neolit123 If you think it is not right. I can close the pr.  :)

**Comment by neolit123** [comment]
i think it's not right, because the root kubeadm folder is not a go module. the only go module is /kinder.
we should even remove the /go.mod file because i don't think it's currently needed.

**Comment by tanjunchen** [comment]
@neolit123  Thank You . I  Will Change it . I will delete the go.mod file  int the root directory If you Need

**Comment by ereslibre** [comment]
/lgtm
/approve
/hold

Agree that this toplevel `go.mod` is not necessary. Holding just in case I'm missing something, @fabriziopandini feel free to unhold.

**Comment by neolit123** [comment]
thanks
/holld canbcel

**Pull request merged**
