### PR TITLE
fixed broken links in documents under design

### PR DESCRIPTION
**Pull request by kundan2707**
fixed broke link.
fixes: #2975

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
are there any other broken links in /design?

**Comment by kundan2707** [comment]
@neolit123  i will check for broken links in design  if any.

**Comment by kundan2707** [comment]
/retitle fixed broken links in documents under design

**Comment by kundan2707** [comment]
@neolit123  there are multiple broken links in design_v1.9.md and .design_v1.8.md too.
I will fix all of them and push changes

**Comment by neolit123** [comment]
> @neolit123 there are multiple broken links in design_v1.9.md and .design_v1.8.md too. I will fix all of them and push changes

please keep the charges in a single pr with one commit

thanks

**Comment by kundan2707** [comment]
> please keep the changes in a single pr with one commit
@neolit123  i will do the same.

**Comment by kundan2707** [comment]
@neolit123  pushed recent changes. PATL.

**Review by neolit123 — COMMENTED** [review]
this update seems good to me. thanks

/lgtm
/approve

**Pull request merged**
