### PR TITLE
kinder: remove -k / -kustomize-dir support and related test jobs

### PR DESCRIPTION
**Pull request by neolit123**
xref https://github.com/kubernetes/kubeadm/issues/2046
test-infra PR: https://github.com/kubernetes/test-infra/pull/19299

### CODE REVIEW

**Review by yagonobre — COMMENTED** [review]
/lgtm

**Comment by neolit123** [comment]
k/k PR merged: https://github.com/kubernetes/kubernetes/pull/94871
test infra PR merged: https://github.com/kubernetes/test-infra/pull/19299

/hold cancel

**Pull request merged**
