### PR TITLE
Replace iouitl with io and os #2593 after remove v1.20 workflows

### LINKED ISSUE #2599: reintroduce the Go io / os package changes once 1.20 goes out of support
1.20 still uses go 1.15.15 for building
which means we cannot have the changes that this PR made:
https://github.com/kubernetes/kubeadm/pull/2593

re-add the changes in the 1.24 cycle after 1.20 goes out of support.

### PR DESCRIPTION
**Pull request by pacoxu**
Depends on #2644 and https://github.com/kubernetes/test-infra/pull/25065 (which will remove v1.20 workflows)

> https://github.com/kubernetes/website/blob/main/content/en/releases/patch-releases.md#120
> End of Life for 1.20 is 2022-02-28 (today).

After 1.20 workflows are removed, we can reapply PR #2593

Fixes #2599

### CODE REVIEW

**Comment by RA489** [comment]
Thanks for this PR. We are good to go after we merge https://github.com/kubernetes/test-infra/pull/25065

**Comment by neolit123** [comment]
/lgtm
/approve
/hold

feel free to `/hold cancel` once https://github.com/kubernetes/test-infra/pull/25065 merges

**Pull request merged**
