### PR TITLE
kinder: upgrade node's kubelet and kubectl last

### PR DESCRIPTION
**Pull request by neolit123**
- Upgrade node kubelet and kubectl last, after the kubeadm binary
is upgraded and after the "kubeadm upgrade" process has finished
on all nodes.

see
https://github.com/kubernetes/kubernetes/issues/86676
https://github.com/kubernetes/kubeadm/issues/1981

deciding on how to proceed here, after https://github.com/kubernetes/kubernetes/issues/86676 sees more discussion.

### CODE REVIEW

**Comment by neolit123** [comment]
> Delete the kubelet checkpoint file before kubelet restart
because in 1.18 the kubelet started panicing (again?) because
of it.

this part is a bug in the kubelet and we must not do it from kinder.
i will update the PR once the related kubelet PRs merge.

**Comment by fabriziopandini** [comment]
> i will update the PR once the related kubelet PRs merge

got it. ping me after the PR is updated for approval

**Comment by neolit123** [comment]
@fabriziopandini 
i have updated this PR

after https://github.com/kubernetes/kubernetes/issues/86676 closed, we no longer have to manually clean the checkpoint file. the PR only changes the upgrade order for the kubelet & kubectl.

/hold cancel

**Pull request merged**
