### PR TITLE
kinder: remove CI workflows for 1.13 and 1.14

### PR DESCRIPTION
**Pull request by neolit123**
- remove 1.13-1.14 upgrade workflows
- remove 1.14-on-1.13 skew workflows
- remove regular and external etcd 1.14 workflows
- move *tasks-automatic-copy-certs.yaml imported workflows to
*tasks.yaml as 1.13 goes out of scope. This enables automatic copy
of certs for all workflows.

/hold
xref https://github.com/kubernetes/kubeadm/issues/1963

test infra PR: https://github.com/kubernetes/test-infra/pull/15576

### CODE REVIEW

**Comment by boluisa** [comment]
mistakenly put lgtm on this PR. sorry!

**Comment by neolit123** [comment]
this is ready to go (1.17.1 is out) but i need to rebase.

**Comment by neolit123** [comment]
@fabriziopandini 
i have updated this PR.

the release team removed the 1.14* jobs in a separate test-infra PR, so i closed: https://github.com/kubernetes/test-infra/pull/15576
also 1.17.1 is out.

**Comment by fabriziopandini** [comment]
@neolit123 thanks!
/approve
/lgtm

**Pull request merged**
