### PR TITLE
add 1.32 kinder workflows

### PR DESCRIPTION
**Pull request by yt-huang**
xref:
  1.32: housekeeping tasks #3097

### CODE REVIEW

**Comment by carlory** [comment]
/hold
for https://kubernetes.io/releases/patch-releases/#1-28

**Comment by neolit123** [comment]
soon this branch will exist:
https://github.com/kubernetes/kubernetes/tree/release-1.32

and here will be a new dashboard called sig-release-1.32-informing:
https://testgrid.k8s.io/sig-release

once that happens run ./hack/update-workflows.sh again and update this PR and send PR for kubernetes/test-infra

cc @pacoxu

**Comment by neolit123** [comment]
@yt-huang please run update-workflows again and update this PR and send the k/test-infra PR.

**Comment by pacoxu** [comment]
> https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubeadm/3112/pull-kubeadm-kinder-verify/1861750520947937280

Found difference in the output; please run `./hack/update-workflows.sh`

**Comment by neolit123** [comment]
assigning non-reponsive contributors to PRs that we need on time is not working well for us.

**Pull request closed without merging**
