### PR TITLE
kinder: cleanup support for v1.11 and v1.12

### PR DESCRIPTION
**Pull request by hypnoglow**
This changeset removes support for k8s 1.11 and 1.12 as proposed in #1866.

~~This is WIP as I wait for a response on [this](https://github.com/kubernetes/kubeadm/issues/1866#issuecomment-548549582) comment.~~

### CODE REVIEW

**Comment by neolit123** [comment]
/approve
this cleanup seems fine to me.

**Comment by fabriziopandini** [comment]
@haibinxie please rebase, then lgtm. well done!

**Comment by fabriziopandini** [comment]
@hypnoglow please rebase, then lgtm

**Comment by hypnoglow** [comment]
Rebased

**Pull request merged**
