### PR TITLE
picture error

### PR DESCRIPTION
**Pull request by LinshanYu**
picture error

### CODE REVIEW

**Comment by dixudx** [comment]
@LinshanYu  Please sign your CLA. Thanks.

**Comment by LinshanYu** [comment]
> @LinshanYu Please sign your CLA. Thanks.

I think there was a mistake that I had signed CLA By name：LinshanYu, but my local gitName is yulinshan. Can you help me to put the pr to LinshanYu, ths ;  I'll deal with the situation

**Comment by LinshanYu** [comment]
> /check-cla

ths

**Comment by neolit123** [comment]
@LinshanYu when you signed the CLA with an email, make sure you add this email to the github account you submit the PR with.

also you need to author the commit with the same github user:
> commit missing GitHub user

**Comment by LinshanYu** [comment]
> @LinshanYu when you signed the CLA with an email, make sure you add this email to the github account you submit the PR with.
> 
> also you need to author the commit with the same github user:
> 
> > commit missing GitHub user

ths, i'll check my CLA

**Pull request closed without merging**
