### PR TITLE
kubeadm: add kinder test jobs for k8s 1.25

### PR DESCRIPTION
**Pull request by RA489**
add kinder test jobs for k8s 1.25
xref: https://github.com/kubernetes/kubeadm/issues/2694
test_infra PR: https://github.com/kubernetes/test-infra/pull/27127

### CODE REVIEW

**Comment by neolit123** [comment]
looks like the ci is failing. i didn't check logs (currently on mobile)

**Comment by pacoxu** [comment]
Some go format failures. I tried to fix it in https://github.com/kubernetes/kubeadm/pull/2744.

**Review by neolit123 — COMMENTED** [review]
/approve

**Comment by neolit123** [comment]
> task-08-e2e-log failed. Needs more investigation.

i think i saw discussion in the #code-organization slack channel about a ginkgo bug with latest go.

**Pull request merged**
