### PR TITLE
kinder: add e2e test workflow for testing the v1beta4.ClusterConfiguration.encryptionAlgorithm

### PR DESCRIPTION
**Pull request by neolit123**
Use an v1beta4.ClusterConfiguration.encryptionAlgorithm with value ECDSA-P256.

only add a "latest" test, we should not backport changes in old branches that might break this.

fixes https://github.com/kubernetes/kubeadm/issues/3073

test infra PR
https://github.com/kubernetes/test-infra/pull/32811

3rd commit also switches the kubeadm jobs to the EKS cluster.
we need to make sure this switch does not add flakes.

### CODE REVIEW

**Comment by neolit123** [comment]
@pacoxu this PR and the test infra PR are also switching to EKS cluster.

**Review by pacoxu — APPROVED** [review]
/lgtm
/unhold

**Comment by pacoxu** [comment]
> @pacoxu this PR and the test infra PR are also switching the jobs to EKS cluster.
> so we need to watch for potential flakes.

If it flakes in EKS clusters, need we switch back again?

**Comment by neolit123** [comment]
> > @pacoxu this PR and the test infra PR are also switching the jobs to EKS cluster.
> > so we need to watch for potential flakes.
> 
> If it flakes in EKS clusters, need we switch back again?

yes.

this ran over the weekend with EKS and there were no flakes
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-latest

**Comment by neolit123** [comment]
also this new test job for encryption algo is green:
https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-encryption-algorithm-latest

**Pull request merged**
