### PR TITLE
kinder: remove 1.17 jobs

### PR DESCRIPTION
**Pull request by RA489**
test-infra PR: https://github.com/kubernetes/test-infra/pull/20531
regular cleanup of e2e tests:
xref https://github.com/kubernetes/kubeadm/issues/2362

### CODE REVIEW

**Comment by fabriziopandini** [comment]
I guess this is the reason why this PR is on hold, but I was expecting more v1.17 jobs being deleted...

**Comment by neolit123** [comment]
removing only these 3 seems correct.

**Review by neolit123 — COMMENTED** [review]
thanks @RA489 
/lgtm
/approve

**Pull request merged**
