### PR TITLE
[kinder] remove dependency yaml.v2

### PR DESCRIPTION
**Pull request by fabriziopandini**
this PR remove dependency from `gopkg.in/yaml.v2` since we are already using `sigs.k8s.io/yaml` in other places

/area clusterctl
/assign @neolit123

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/hold 
it seems there are differences in the serialization of `time.Duration` 🤔

**Comment by neolit123** [comment]
> it seems there are differences in the serialization of time.Duration

seems like so.

**Comment by neolit123** [comment]
sigs.k8s.io/yaml uses encoding/json as it's JSON backend. so this will work.
https://play.golang.org/p/GbC4QLJCPCG
it needs some special handling.

**Comment by neolit123** [comment]
@fabriziopandini i will send the PR for the above.
/close

**Pull request closed without merging**
