### PR TITLE
Add e2e jobs for v1.27

### PR DESCRIPTION
**Pull request by SataQiu**
Add kubeadm e2e jobs for v1.27.

ref: #2799 kubernetes/test-infra#29128

/hold

### CODE REVIEW

**Comment by pacoxu** [comment]
/lgtm
Should we wait until version 1.27.0 is released before proceeding with it?

**Comment by neolit123** [comment]
> Should we wait until version 1.27.0 is released before proceeding with it?

we need the k/k release-x branch and test grid dashboards.

**Comment by SataQiu** [comment]
The k/k `release-1.27` branch has been created, let's wait for the test grid dashboards to be created.

**Comment by SataQiu** [comment]
It seems that the test grid dashboards was created by kubernetes/test-infra#29172

**Pull request merged**
