### PR TITLE
Cleanup E2E jobs for 1.20

### PR DESCRIPTION
**Pull request by RA489**
Cleanup E2E jobs for 1.20
xref: https://github.com/kubernetes/kubeadm/issues/2621

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
looks like 1.20 has ~28 more days before EOF:

https://kubernetes.io/releases/#release-history

```
1.20
Latest Release:1.20.14 (released: 2021-12-15)
End of Life:2022-02-28
```

**Comment by RA489** [comment]
@kubernetes/sig-cluster-lifecycle-pr-reviews
looking for LGTM. thanks.

**Comment by neolit123** [comment]
Does anyone know if sig release confirmed this will be the last 1.20 patch
release? Trying to understand if the website info is accurate..

**Comment by RA489** [comment]
> last 1.20 patch release

https://kubernetes.io/releases/patch-releases/#1-20

**Comment by RA489** [comment]
> Does anyone know if sig release confirmed this will be the last 1.20 patch release? Trying to understand if the website info is accurate..

https://kubernetes.io/releases/patch-releases/#1-20

**Pull request merged**
