### PR TITLE
Cleanup E2E jobs for 1.18

### PR DESCRIPTION
**Pull request by CaoDonghui123**
Cleanup E2E jobs for 1.18
xref: #2440
kubernetes/test-infra#21905

/area kinder
/kind cleanup

### CODE REVIEW

**Comment by neolit123** [comment]
/hold

apparently there will be another last 1.18.x release.
let's hold until that version is out and we can test it for a while.
sorry for the inconvenience.

**Comment by pacoxu** [comment]
As https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#118
> End of Life for 1.18 is 2021-05-12

**Comment by pacoxu** [comment]
As https://github.com/kubernetes/sig-release/blob/master/releases/patch-releases.md#118
> End of Life for 1.18 is 2021-05-12

**Comment by neolit123** [comment]
@CaoDonghui123 can you please update the test infra PR and we can then merge both of these.

https://github.com/kubernetes/test-infra/pull/21905

**Pull request merged**
