### PR TITLE
WIP: Move kubeadm over here

### PR DESCRIPTION
**Pull request by luxas**
This work/PR isn't done before we've merged all pending PRs into kubernetes core, but showing the progress here

@kubernetes/sig-cluster-lifecycle

### CODE REVIEW

**Comment by luxas** [comment]
How can we fix the bot to allow others to commit in the same PR?
(Well it's not blocking, but anyway)

**Comment by thockin** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubeadm/72)

**Comment by luxas** [comment]
What's that @thockin :)?
Machine or human-generated?

**Comment by thockin** [comment]
Sorry, I turned on reviewable for this repo, if people want to use it.

**Comment by resouer** [comment]
@luxas Is this still active?

**Comment by roberthbailey** [comment]
I think we should close this PR. @pipejakob has started drafting a plan for how we can migrate kubeadm out of the main repo.

**Comment by luxas** [comment]
Ok @roberthbailey, @pipejakob please ping me when you have something...

**Pull request closed without merging**
