### PR TITLE
kinder: remove kube dns support

### PR DESCRIPTION
**Pull request by wangyysde**
Signed-off-by: wangyysde <net_use@bzhy.com>
Fix: #2484
we removed kube-dns support in kubeadm 1.21,so remove kube-dns support in kinder.
/kind cleanup
/kind feature

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/lgtm
/hold
For @neolit123 to take a look

**Comment by wangyysde** [comment]
@ neolit123 Thanks. I will clean all kubedns in kinder.

**Comment by neolit123** [comment]
/hold cancel
if we missed something let's clean it in a follow up.

**Pull request merged**
