### PR TITLE
Step1: Remove offensive words from CI jobs configuration

### PR DESCRIPTION
**Pull request by SataQiu**
Ref: #2302
XRef: kubernetes/test-infra#19381

TODO: Remove the old configuration after kubernetes/test-infra#19381 merged.

### CODE REVIEW

**Comment by SataQiu** [comment]
After kubernetes/test-infra#19381 is merged,  `pull-kubeadm-kinder-upgrade-master` will be succeeded.

**Comment by neolit123** [comment]
thanks @SataQiu 
let's change the new files from [here](https://github.com/kubernetes/kubeadm/pull/2298) once it merges.

/hold

**Comment by neolit123** [comment]
> Error: invalid workflow file: /home/prow/go/src/github.com/kubernetes/kubeadm/kinder/ci/workflows/presubmit-upgrade-master.yaml does not exist

note, this PR won't be able to merge without renaming `presubmit-upgrade-master.yaml`

**Comment by neolit123** [comment]
https://github.com/kubernetes/kubeadm/pull/2298 merged.

**Comment by SataQiu** [comment]
> > Error: invalid workflow file: /home/prow/go/src/github.com/kubernetes/kubeadm/kinder/ci/workflows/presubmit-upgrade-master.yaml does not exist
> 
> note, this PR won't be able to merge without renaming `presubmit-upgrade-master.yaml`

@neolit123 I think we can add the new configuration first, wait until kubernetes/test-infra#19381 is merged, then the new configuration will be used, we can remove the old configuration safely. Is that right?

**Comment by neolit123** [comment]
Yes, that should work.

**Pull request merged**
