### PR TITLE
error link 

### PR DESCRIPTION
**Pull request by LinshanYu**
the link error

### CODE REVIEW

**Comment by neolit123** [comment]
can you fix the `docs/design/design_v1.9.md` error in the same PR?
you can use `git commit --amend` and `git push -f <remote-branch>` to force push the same commit after it includes both changes.

**Comment by LinshanYu** [comment]
> can you fix the `docs/design/design_v1.9.md` error in the same PR?
> you can use `git commit --amend` and `git push -f <remote-branch>` to force push the same commit after it includes both changes.

Sry ,  the pr of docs/design/design_v1.9.md was commited  by my local git name ,which don't signed by CLA .

**Comment by neolit123** [comment]
just add the 1.9 change to your `picerr2` branch.

**Comment by LinshanYu** [comment]
> just add the 1.9 change to your `picerr2` branch.

ok,ths

**Pull request closed without merging**
