### PR TITLE
kinder: update test workflow for 1.29

### PR DESCRIPTION
**Pull request by liangyuanpeng**
kinder: update test workflow for 1.29.
Part of https://github.com/kubernetes/kubeadm/issues/2910
PR of test-infra side: https://github.com/kubernetes/test-infra/pull/31194

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
this has to be done after the 21st nov. the k/kubeadm issue says "after the ... branch is created"
https://github.com/kubernetes/sig-release/tree/master/releases/release-1.29

/hold

**Comment by liangyuanpeng** [comment]
I‘m understand it is need the 1.29 is released and Sorry for the confusion of have not make it clear.

**Review by neolit123 — COMMENTED** [review]
> kinder: update test workflow for 1.29. Part of #2910 PR of test-infra side: [kubernetes/test-infra#31194](https://github.com/kubernetes/test-infra/pull/31194)

@liangyuanpeng the kubernetes/kubernetes release-1.29 branch already exists, but the test-grid for release 1.29 is not created yet. we expect it to be created today.

please run the update-workflows.sh script again and apply any additional diff to this PR and the test-infra PR.

/ok-to-test

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
