### PR TITLE
delete go.mod in root directory

### PR DESCRIPTION
**Pull request by hwdef**
Fix #1813  again

### CODE REVIEW

**Comment by fabriziopandini** [comment]
The go-mod file in the root directory gets automatically generate when updating go modules under `kinder/` or `operator/`, so IMO there is no point in continuing to delete it
I'm +1 for closing this PR

**Comment by hwdef** [comment]
Maybe you can find a way to not generate it.

**Comment by fabriziopandini** [comment]
Feel free to open an issue and propose other solutions, but please take care such solutions are not adding any burden to people working in this repo.
In the meantime, I don't see any problem in keeping the file

**Comment by hwdef** [comment]
fine.

just close this.

**Comment by hwdef** [comment]
@fabriziopandini 
What commond did you used?
I try to update go modules under `kinder/` or `operator/`, but go.mod in root directory is not recreate.

**Comment by hwdef** [comment]
/assign @neolit123

Can you give me some suggestions?
Or we can add go.mod to .gitignore.

**Comment by fabriziopandini** [comment]
TBH, it will be really weird for me to have go.mod in .gitignore

As explained before, as a maintainer of this project, I don't see problems in having this file, and I don't want this to get into the way of contributors again given that after the first PR got merged it was regenerated by simply working on kinder/on the operator.

Also, as soon as the details about the move of kubeadm out of K/K will be addressed, this file will be required, so any effort to remove it is just temporary.

I'm -1 to get this merged
🤷‍♂️

**Comment by hwdef** [comment]
It is wrong to keep files just because there are no problems, and it will cause more and more garbage.
I looked at the file history, this file was submitted by you, and it is not surprising that you object to cleaning it.
Maybe others do not agree to clean up this file, but I still think that you uploaded this file as a mistake.
You can +1 or -1, but please don’t promote bad habits.

**Comment by hwdef** [comment]
@fabriziopandini 
And please let me ask again, what command did you use to upgrade? Did you make a mistake that caused this file to be generated?

**Comment by fabriziopandini** [comment]
> what command did you use to upgrade? Did you make a mistake that caused this file to be generated?

The file was generated working on the operator, but TBH I don't remember if this happened while updating some reference or by running some hack/verify script.
However this is going to be revised as per https://github.com/kubernetes/kubeadm/issues/2317, and this will revamp most of the initial experiment + update to the latest version of golang, so might be the problem will be fixed during this effort

**Comment by neolit123** [comment]
The file is not needed in general since the root folder is not a module. I
can confirm that something generates it under certain conditions. Instead
of this pr if you can find what of our scripts generates it and change that
behavior it would be the better fix.

**Comment by fabriziopandini** [comment]
I just gave another try at this while working on kinder and immediatebly stumbled into
```
package k8s.io/kubeadm: no Go files in /Users/fpandini/go/src/k8s.io/kubeadm
```
when doing `go install` from the kinder folder

**Pull request closed without merging**
