### PR TITLE
correct the file name: schedler.conf->scheduler.conf

### PR DESCRIPTION
**Pull request by AdamDang**
schedler.conf->schedler.conf

### CODE REVIEW

**Comment by neolit123** [comment]
@AdamDang 
are you familiar with squashing commits?
https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

please make the 3 commits a single commit.

if not we can try `tide/squash`.

**Comment by AdamDang** [comment]
So sorry, I have no experience on squashing.
Please deal with this PR in your way. 
Thanks!

**Comment by neolit123** [comment]
@AdamDang i see you send a lot of PRs for k8s, but you have to try squash eventually!
otherwise some PRs will get rejected...

/tide squash

**Comment by neolit123** [comment]
looks like `tide/squash` cannot be added via a command.

**Comment by AdamDang** [comment]
@neolit123  
I've tried  to squashed. does it works?
I made a mistake that squashed 4 commits not 3 in this PR :(

**Comment by neolit123** [comment]
> I've tried to squashed. does it work?
nope, the squash seems to have included a commit from another user and we don't what that.

you can create a repository in your account and experiment with squash there?
then get back to this and try to fix it?

usually the workflow is:
```
git rebase -i HEAD~N 
# where N means how many commits to squash
# it shows you an interactive editor - mark the commits near the bottom with 's' or 'f' and leave on on top
# then do a:
git push -f ....
```

**Comment by AdamDang** [comment]
@neolit123 
Yes, I noticed it. I should use HEAD~3, but Used HEAD~4. That's the point.
I will recreate this PR and redo a squashing. :)
Thanks a lot!

**Comment by neolit123** [comment]
@AdamDang if you recreate this PR might as well only have the change in the 3 files in a single commit.
e.g. using a local text editor and not using the web UI?

**Comment by AdamDang** [comment]
I've recreated the PR. 
It works. 3 commits in a PR has become to 1 commit. :)

**Pull request closed without merging**
