### PR TITLE
Add a GitHub issue template

### PR DESCRIPTION
**Pull request by everett-toews**
Modeled after https://github.com/kubernetes/kubernetes/blob/master/.github/ISSUE_TEMPLATE.md

### CODE REVIEW

**Comment by everett-toews** [comment]
Sigh. I thought I had jumped through all of the CLA signing hoops correctly. I'll go get this sorted out.

**Comment by everett-toews** [comment]
Recheck

**Comment by everett-toews** [comment]
@k8s-ci-robot I signed it!

**Comment by everett-toews** [comment]
@k8s-bot ok to test

**Comment by everett-toews** [comment]
@k8s-ci-robot ok to test

**Comment by everett-toews** [comment]
@k8s-ci-robot ok to test

**Comment by everett-toews** [comment]
I can't tell if @k8s-ci-robot is ignoring me or if my CLA stuff is still borked.

**Comment by luxas** [comment]
I have no idea why it's failing.
cc @foxish

**Comment by everett-toews** [comment]
@luxas @foxish Thanks for taking a look at this. 

Currently we think it has to do with our unsigned CCLA. We're waiting on confirmation from the Linux Foundation folks as they're the only one's with visibility into this stuff. Hopefully we'll get the remediation steps along with that confirmation too.

I'll comment on this PR and remove the silly "Commit to trigger CI" commit as soon as we hear back.

**Comment by everett-toews** [comment]
I signed it

**Comment by everett-toews** [comment]
@luxas @foxish The CCLA issue has been sorted out and I removed the superfluous commit. This is RFR. Thanks for your patience!

**Comment by luxas** [comment]
cc @idvoretskyi @jbeda Does this look good to you?

LGTM

**Comment by luxas** [comment]
Perfect, merging...

**Pull request merged**
