### PR TITLE
Fix self-hosting flag

### PR DESCRIPTION
**Pull request by ueokande**
`—features-gates=self-hosting` -> `--features-gates=SelfHosting`

### CODE REVIEW

**Comment by timothysc** [comment]
@ueokande in order for us to accept you will need to sign the CNCF CLA.

**Comment by ueokande** [comment]
@timothysc sorry to late.
I registerred my information to CNCF CLA, but I found a misspelt my name in the agreement after that (I just mistook on the registration).
I sent an email to `e-signing@linuxfoundation.org` to emit the agreement with my new profile, but It does not come reply.
What should I do?

**Comment by neolit123** [comment]
@ueokande 
try contacting cncf?
https://www.cncf.io/about/contact/

**Comment by ueokande** [comment]
@neolit123 thanks, I'll try it

**Comment by ueokande** [comment]
I signed CLA and force-pushed my changes.

**Comment by neolit123** [comment]
@ueokande thank you for fixing your CLA.

/lgtm

**Pull request merged**
